#!/bin/bash

# This test file is executed against an auto-generated devcontainer.json that
# includes the 'personal-features' Feature alone (it has no options - this
# Feature is the owner's personal, opinionated setup, so everything below is
# always installed).
#
# Installing Claude Code requires npm, so the autogenerated job in
# .github/workflows/test.yaml runs this against Node-enabled base images
# rather than bare debian/ubuntu - see src/personal-features/NOTES.md for why
# Node isn't bundled into this Feature itself.
#
# This test can be run with the following command:
#
#    devcontainer features test \
#               --features personal-features \
#               --remote-user root \
#               --skip-scenarios \
#               --base-image mcr.microsoft.com/devcontainers/javascript-node:latest \
#               /path/to/this/repo

set -e

# shellcheck source=/dev/null  # dev-container-features-test-lib is injected by the test harness at runtime; not resolvable statically. check()/reportResults() come from it.
source dev-container-features-test-lib

check "claude wrapper is on PATH and executable" bash -c "test -x \"\$(command -v claude)\""
check "claude reports a version" claude --version

# The wrapper injects --ide ONLY for a bare interactive session (no args + TTY)
# and passes everything else straight through, so a new Claude Code subcommand
# can never be mangled into `claude --ide <subcommand>` (see NOTES.md). Assert
# the guard (`$# -eq 0` + `[ -t 0 ]`) and the verbatim passthrough exec are
# present, and that no stale subcommand allowlist (`case "$1" in`) survives.
check "wrapper injects --ide only for a bare interactive session" bash -c \
  "grep -qF -- '\$# -eq 0' \"\$(command -v claude)\" && grep -qF -- '[ -t 0 ]' \"\$(command -v claude)\" && grep -qF -- 'exec \"\$REAL\" --ide' \"\$(command -v claude)\""
check "wrapper passes everything else (subcommands, flags, prompts) through untouched" bash -c \
  "grep -qF -- 'exec \"\$REAL\" \"\$@\"' \"\$(command -v claude)\""
check "wrapper has no hardcoded subcommand allowlist" bash -c \
  "! grep -qF 'case \"\$1\" in' \"\$(command -v claude)\""

check "claude config dir exists" bash -c "test -d /usr/local/share/claude-home"
check "gh config dir exists" bash -c "test -d /usr/local/share/gh-cli-config"
check "odoo-sdk config dir exists" bash -c "test -d /usr/local/share/odoo-sdk-config"
check "CLAUDE_CONFIG_DIR points at the bind mount" bash -c "[ \"\$CLAUDE_CONFIG_DIR\" = '/usr/local/share/claude-home' ]"
check "GH_CONFIG_DIR points at the bind mount" bash -c "[ \"\$GH_CONFIG_DIR\" = '/usr/local/share/gh-cli-config' ]"

# #239: the SDK config env var is the uppercase ODOO_SDK_CONFIG pointing at the
# mount DIRECTORY (the SDK probes it for config.toml/config.ini). The old
# lowercase odoo_sdk_CONFIG (which pointed at a specific config.ini file) must be
# gone - a case-sensitive stale name would leave the SDK reading nothing.
check "ODOO_SDK_CONFIG points at the bind mount dir" bash -c \
  "[ \"\$ODOO_SDK_CONFIG\" = '/usr/local/share/odoo-sdk-config' ]"
check "legacy lowercase odoo_sdk_CONFIG is not set" bash -c "[ -z \"\$odoo_sdk_CONFIG\" ]"

# NOTE: no check here that the odoo-sdk MCP server is registered. install.sh
# registers it at BUILD time into CLAUDE_CONFIG_DIR=/usr/local/share/claude-home,
# but at RUNTIME that directory is shadowed by the feature's bind mount of the
# host's ~/.claude (empty on CI runners and fresh hosts), so `claude mcp get
# odoo-sdk` reports the server as missing whenever the mount is active - i.e.
# always in real use. Asserting it here would test something the feature cannot
# deliver; a runtime-registration mechanism (e.g. a feature-contributed
# postCreateCommand) is a separate product decision.

# Regression guard for #120: the odoo-tui curses TUI console script is symlinked
# onto PATH whenever the SDK is installed (i.e. whenever odoo-mcp is present).
# Gated on the odoo-mcp binary so it no-ops on <3.10 base images where the SDK
# wheel isn't installed. PATH checks are unaffected by the bind mounts above.
check "odoo-tui console script is on PATH when the SDK is installed" bash -c \
  "! test -x /usr/local/bin/odoo-mcp || test -x \"\$(command -v odoo-tui)\""

# #369: the central tracker DB is HOST-provisioned and bind-mounted; the
# container consumes it and never creates one. This reverses the #115 stance
# (which wrongly concluded the state dir couldn't be mounted): updateRemoteUserUID
# remaps the user at container-create so bind mounts line up - the six credential
# mounts already prove it - and install.sh must NOT pre-create the tracker target
# (provision=host in persisted-paths.tsv), or a broken mount would masquerade as a
# working one behind an empty container-local DB. CI runs `sh ./setup.sh` on the
# runner before this test, so the host dir + schema exist and the mount delivers
# them at $ODOO_TASK_TRACKER_DIR.
#
# #552/#533: both checks used to gate on `! command -v odoo-sdk || {...}`, but
# install.sh symlinks only odoo-mcp/odoo-tui onto PATH - `odoo-sdk` never
# resolves, so the guard short-circuited to a vacuous exit 0 and NEITHER body had
# ever executed. They now gate on the real "is the SDK installed at all"
# condition the :69 check uses (/usr/local/bin/odoo-mcp, absent on <3.10 base
# images where the wheel is skipped) and invoke the CLI at its uv-managed venv
# path, the same one the #411 e2e check below resolves.
_SDK_CLI=/usr/local/share/uv/tools/odoo-sdk/bin/odoo-sdk

# POSITIVE: with the mount live, `odoo-sdk log-event` writes into the central DB.
# A missing/unmounted DB would make log-event exit non-zero (the hard error
# below), so a successful write that lands tracker.db at the mounted path is the
# rebuild-surviving derivation reachability of acceptance #3. No
# --attach-active-run, so the row stays untargeted and accrues no billable time
# against a real run if this ever runs against a host-provisioned DB.
check "odoo-sdk log-event writes to the host-provisioned central tracker DB" bash -c \
  "! test -x /usr/local/bin/odoo-mcp || { $_SDK_CLI log-event --source claude:SessionStart --subject ci-positive && test -f \"\$ODOO_TASK_TRACKER_DIR/tracker.db\"; }"

# NEGATIVE: point the state root at an empty dir with no host-provisioned DB; the
# SDK must refuse to self-create one and fail with the single actionable error
# naming the expected path (acceptance #4), never exiting 0 silently. Chained
# with && (not ;) so the non-zero-exit half is actually asserted: `check` runs
# the body in a child shell that does not inherit this file's `set -e`.
check "odoo-sdk refuses to self-create a missing central tracker DB" bash -c \
  "! test -x /usr/local/bin/odoo-mcp || { d=\"\$(mktemp -d)\"; ! ODOO_TASK_TRACKER_DIR=\"\$d\" $_SDK_CLI log-event --source claude:SessionStart --subject ci-negative 2>\"\$d/err\" && grep -q \"\$d/tracker.db\" \"\$d/err\" && ! test -f \"\$d/tracker.db\"; }"

# productivity/navigation CLIs
check "ripgrep is installed" rg --version
check "fd is installed" fd --version
check "fzf is installed" fzf --version
check "bat is installed" bat --version
check "jq is installed" jq --version
check "yq is installed" yq --version
check "eza is installed" eza --version
check "zoxide is installed" zoxide --version
check "tldr is installed" tldr --version
check "qsv is installed" qsv --version

# git QoL tools
check "delta is installed" bash -c "test -x \"\$(command -v delta)\" && delta --version"
check "lazygit is installed" bash -c "test -x \"\$(command -v lazygit)\" && lazygit --version"

# secret scanning
check "gitleaks is installed" gitleaks version

# create-pr (config-driven gh pr create wrapper)
check "create-pr is installed and executable" bash -c "test -x /usr/local/bin/create-pr"
check "create-pr passes shell syntax check" bash -c "sh -n /usr/local/bin/create-pr"
check "PR_AUTOMATION_CONFIG_DIR points at the bind mount" bash -c \
  "[ \"\$PR_AUTOMATION_CONFIG_DIR\" = '/usr/local/share/pr-automation' ]"
check "pr-automation config dir exists" bash -c "test -d /usr/local/share/pr-automation"

# CodeRabbit CLI (best-effort install; check the binary is present + on PATH)
check "coderabbit is installed" bash -c "test -x \"\$(command -v coderabbit)\""
check "coderabbit config dir exists" bash -c "test -d /usr/local/share/coderabbit-config"
check "CODERABBIT_CONFIG_DIR points at the bind mount" bash -c "[ \"\$CODERABBIT_CONFIG_DIR\" = '/usr/local/share/coderabbit-config' ]"

# global git hooks
check "global core.hooksPath is configured" bash -c "[ \"\$(git config --system --get core.hooksPath)\" = '/usr/local/share/git-hooks' ]"
check "global commit-msg hook is executable" bash -c "test -x /usr/local/share/git-hooks/commit-msg"
check "global pre-commit hook is executable" bash -c "test -x /usr/local/share/git-hooks/pre-commit"

# delta wired in as git's pager machine-wide (--system scope)
check "git core.pager is set to delta" bash -c \
  "[ \"\$(git config --system --get core.pager)\" = 'delta' ]"
check "git interactive.diffFilter uses delta" bash -c \
  "[ \"\$(git config --system --get interactive.diffFilter)\" = 'delta --color-only' ]"

# shell enhancements
check "starship is installed" starship --version
check "shell history dir exists" bash -c "test -d /usr/local/share/shell-history"
# shellcheck disable=SC2088  # literal ~ in a human-readable test description, not a path to expand
check "~/.bash_history is linked to the bind-mounted history file" bash -c \
  "[ \"\$(readlink -f \"\$HOME/.bash_history\")\" = '/usr/local/share/shell-history/bash_history' ]"

# Regression guard for #198: shell history is bind-mounted as a *directory*, not
# as a single file. Docker Desktop materialises a missing single-file mount
# source as a directory on the host, which then fails the mount - so the mount
# target must be the directory, with the history file living inside it.
check "shell history mount target is a directory, not a file" bash -c \
  "test -d /usr/local/share/shell-history && ! test -L /usr/local/share/shell-history"

# Regression guard for #198: on a first run against an empty host directory the
# history file doesn't exist yet, so the ~/.bash_history symlink is dangling.
# That has to self-heal - bash opens HISTFILE with O_CREAT, which follows the
# symlink and creates the target. Simulate it by removing the file first.
check "a dangling history symlink self-heals on first write" bash -c \
  "rm -f /usr/local/share/shell-history/bash_history \
   && printf 'echo 198\n' >> \"\$HOME/.bash_history\" \
   && test -f /usr/local/share/shell-history/bash_history"

# Regression guard for #198: HISTFILE is set system-wide (so history persists
# for every user, not just the one whose home was symlinked), and histappend is
# a correctness fix - without it bash truncates HISTFILE on exit and rewrites it
# from memory, so one shell exiting would wipe a concurrent container's history.
check "HISTFILE points at the bind-mounted history file" bash -c \
  "grep -q '^export HISTFILE=/usr/local/share/shell-history/bash_history$' /etc/bash.bashrc"
check "histappend is enabled so concurrent shells don't truncate history" bash -c \
  "grep -q '^shopt -s histappend$' /etc/bash.bashrc"

# Regression guard for #198: assert the *runtime* value, not just the file. Both
# `starship init` and `zoxide init` overwrite PROMPT_COMMAND, so if the flush is
# set before them in the snippet it is silently dropped and history is only
# written on a clean exit (losing it whenever the container is killed).
# /etc/bash.bashrc is guarded by `[ -z "$PS1" ] && return`, so this has to run an
# interactive shell to see the assembled value at all.
check "history -a survives starship/zoxide clobbering PROMPT_COMMAND" bash -ic \
  "[[ \$PROMPT_COMMAND == *'history -a'* ]]"

check "starship.toml was placed in global share" bash -c "test -f /usr/local/share/starship.toml"
check "shell snippet was appended to global bashrc" bash -c "grep -q 'personal-features' /etc/bash.bashrc"

# Claude consulting skills delivery (feature-owned namespace). install.sh stages
# the shipped skills at a build-time location OUTSIDE the CLAUDE_CONFIG_DIR bind
# mount; sync-claude-skills (feature-contributed postCreateCommand) publishes
# them into $CLAUDE_CONFIG_DIR/skills once the mount is active. Smoke assertions
# ONLY - the staging dir exists and the sync script is installed, executable, and
# syntactically valid. Full sync behaviour (temp CLAUDE_CONFIG_DIR, decoy-skill
# survival, idempotency) is covered by a separate test sub-issue; the sync itself
# doesn't run under `devcontainer features test` (no postCreateCommand there).
check "personal-features skills share dir exists" bash -c "test -d /usr/local/share/personal-features/skills"
check "sync-claude-skills is installed and executable" bash -c "test -x /usr/local/bin/sync-claude-skills"
check "sync-claude-skills passes shell syntax check" bash -c "bash -n /usr/local/bin/sync-claude-skills"

# --- sync-claude-skills behaviour (#252) --------------------------------------
# The smoke checks above prove the pieces exist; these exercise what the sync
# actually DOES, all against THROWAWAY directories - never the real
# $CLAUDE_CONFIG_DIR. sync-claude-skills takes its staging source from
# PERSONAL_FEATURES_SKILLS_DIR (default /usr/local/share/personal-features/
# skills), so the behavioural checks point it at a FIXTURE staging tree built
# here. That keeps them deterministic and independent of which real skills have
# shipped so far (the shipped namespace may still be README-only mid-epic).

# Strengthen the staging smoke check: whatever SKILL.md the build staged (if any)
# must be a regular, readable file - never a dir or a dangling symlink. Passes
# vacuously while the namespace is still README-only (the glob matches nothing).
check "any staged SKILL.md is a regular readable file" bash -c \
  "for f in /usr/local/share/personal-features/skills/*/SKILL.md; do [ -e \"\$f\" ] || continue; test -f \"\$f\" && test -r \"\$f\" || exit 1; done"

# Build a deterministic fixture staging tree + a throwaway CLAUDE_CONFIG_DIR the
# behavioural checks share, then seed the config with a DECOY user-authored skill
# (must survive) and a STALE copy of a shipped name (wrong content, must be
# replaced). mktemp keeps it all off the real config dir.
SKILLS_TEST_ROOT="$(mktemp -d)"
FIXTURE_STAGING="$SKILLS_TEST_ROOT/staging"
FIXTURE_CONFIG="$SKILLS_TEST_ROOT/claude-home"
mkdir -p \
  "$FIXTURE_STAGING/fixture-quote-draft" \
  "$FIXTURE_STAGING/fixture-design-doc" \
  "$FIXTURE_STAGING/fixture-not-a-skill" \
  "$FIXTURE_CONFIG/skills/my-own-skill" \
  "$FIXTURE_CONFIG/skills/fixture-quote-draft"
printf 'shipped quote-draft v2\n'  > "$FIXTURE_STAGING/fixture-quote-draft/SKILL.md"
printf 'shipped design-doc\n'       > "$FIXTURE_STAGING/fixture-design-doc/SKILL.md"
printf 'design-doc template\n'      > "$FIXTURE_STAGING/fixture-design-doc/template.md"
printf 'loose notes, no SKILL.md\n' > "$FIXTURE_STAGING/fixture-not-a-skill/notes.txt"
printf '# skills readme\n'          > "$FIXTURE_STAGING/README.md"
printf 'my hand-written skill - do not touch\n' > "$FIXTURE_CONFIG/skills/my-own-skill/SKILL.md"
printf 'STALE quote-draft v1\n'                 > "$FIXTURE_CONFIG/skills/fixture-quote-draft/SKILL.md"

# The default (non-override) code path must run cleanly against the REAL staging
# dir into a fresh temp config: it either syncs whatever shipped or no-ops (exit
# 0) when the namespace is still empty. Proves the production path, not just the
# fixture one.
check "sync runs cleanly against the real staging dir into a temp config" bash -c \
  "CLAUDE_CONFIG_DIR=\"$SKILLS_TEST_ROOT/real-run-home\" /usr/local/bin/sync-claude-skills"

# Publish the fixture skills into the temp config (this run is itself asserted).
check "sync publishes fixture skills into a temp CLAUDE_CONFIG_DIR" bash -c \
  "PERSONAL_FEATURES_SKILLS_DIR=\"$FIXTURE_STAGING\" CLAUDE_CONFIG_DIR=\"$FIXTURE_CONFIG\" /usr/local/bin/sync-claude-skills"

# Shipped skills land byte-identical to staging (single- and multi-file).
check "a shipped skill lands with content matching staging exactly" bash -c \
  "diff -r \"$FIXTURE_STAGING/fixture-quote-draft\" \"$FIXTURE_CONFIG/skills/fixture-quote-draft\""
check "a shipped multi-file skill lands complete and matching staging" bash -c \
  "diff -r \"$FIXTURE_STAGING/fixture-design-doc\" \"$FIXTURE_CONFIG/skills/fixture-design-doc\""

# The stale copy of a shipped name is overwritten (delete-then-copy), not merged.
check "a stale shipped skill is overwritten by the staged version" bash -c \
  "grep -q 'shipped quote-draft v2' \"$FIXTURE_CONFIG/skills/fixture-quote-draft/SKILL.md\" && ! grep -q STALE \"$FIXTURE_CONFIG/skills/fixture-quote-draft/SKILL.md\""

# The decoy user-authored skill survives untouched (feature-owned namespace only).
check "a user-authored (decoy) skill survives the sync untouched" bash -c \
  "grep -q 'do not touch' \"$FIXTURE_CONFIG/skills/my-own-skill/SKILL.md\""

# A staging subdir with no SKILL.md is not a skill and is never published.
check "a staging subdir without a SKILL.md is ignored" bash -c \
  "! test -e \"$FIXTURE_CONFIG/skills/fixture-not-a-skill\""

# Idempotency: snapshot the synced tree, run the sync again, assert nothing moved
# (diff -r finds no differences between the snapshot and the re-synced tree).
cp -R "$FIXTURE_CONFIG/skills" "$SKILLS_TEST_ROOT/idem-before"
check "sync is idempotent (a second run leaves the skills tree byte-identical)" bash -c \
  "PERSONAL_FEATURES_SKILLS_DIR=\"$FIXTURE_STAGING\" CLAUDE_CONFIG_DIR=\"$FIXTURE_CONFIG\" /usr/local/bin/sync-claude-skills && diff -r \"$SKILLS_TEST_ROOT/idem-before\" \"$FIXTURE_CONFIG/skills\""

# Feature-owned-namespace tradeoff: sync only ever replaces names CURRENTLY in
# staging and never deletes others. So a skill dropped from staging and re-synced
# is deliberately ORPHANED - its previously-synced copy survives, as does a skill
# still shipping. Assert that documented behaviour as-is.
rm -rf "$FIXTURE_STAGING/fixture-quote-draft"
check "a skill removed from staging is orphaned, not deleted, on re-sync" bash -c \
  "PERSONAL_FEATURES_SKILLS_DIR=\"$FIXTURE_STAGING\" CLAUDE_CONFIG_DIR=\"$FIXTURE_CONFIG\" /usr/local/bin/sync-claude-skills && test -f \"$FIXTURE_CONFIG/skills/fixture-quote-draft/SKILL.md\" && test -f \"$FIXTURE_CONFIG/skills/fixture-design-doc/SKILL.md\""

rm -rf "$SKILLS_TEST_ROOT"

# --- Claude Code lifecycle hooks delivery (#327) ------------------------------
# install.sh installs the hook shim (claude-event-hook) and the settings merge
# script (sync-claude-hooks) to /usr/local/bin (outside the CLAUDE_CONFIG_DIR
# bind mount). sync-claude-hooks (feature-contributed postCreateCommand, after
# sync-claude-skills) merges the feature-owned hooks block into the live
# $CLAUDE_CONFIG_DIR/settings.json once the mount is active. Smoke assertions
# first: both scripts exist, are executable, and are syntactically valid. The
# merge itself doesn't run under `devcontainer features test` (no
# postCreateCommand there), so the behavioural checks below drive it by hand
# against a THROWAWAY config dir - never the real $CLAUDE_CONFIG_DIR.
check "claude-event-hook is installed and executable" bash -c "test -x /usr/local/bin/claude-event-hook"
check "claude-event-hook passes shell syntax check" bash -c "bash -n /usr/local/bin/claude-event-hook"
check "sync-claude-hooks is installed and executable" bash -c "test -x /usr/local/bin/sync-claude-hooks"
check "sync-claude-hooks passes shell syntax check" bash -c "bash -n /usr/local/bin/sync-claude-hooks"

# The hook shim must skip PreToolUse for the odoo-sdk MCP server's own tools (it
# logs those dispatches server-side, #326/#340) and must still log every other
# tool. This used to be `grep -q 'mcp__odoo__\*'` against the shim text, which
# passed *precisely because* the glob was the broken `mcp__odoo__*` and would
# have FAILED the moment it was corrected - rubber-stamping a guard that never
# matched a real tool name, so odoo calls were double-logged (#529/#551).
#
# Assert the emitted command line instead. `odoo-sdk` is stubbed onto PATH so the
# shim resolves it and records the argv it built; no real SDK is needed. Claude
# Code namespaces MCP tools as `mcp__<server-key>__<tool>` with the key's hyphens
# preserved, and install.sh registers the key `odoo-sdk`, so
# `mcp__odoo-sdk__get_tasks` below is a production-shaped tool name.
HOOK_STUB_ROOT="$(mktemp -d)"
mkdir -p "$HOOK_STUB_ROOT/bin"
cat > "$HOOK_STUB_ROOT/bin/odoo-sdk" <<'STUB'
#!/bin/sh
# Stand-in for the real CLI: one line per invocation, recording the whole argv.
printf '%s\n' "$*" >> "$HOOK_STUB_LOG"
STUB
chmod +x "$HOOK_STUB_ROOT/bin/odoo-sdk"
export HOOK_STUB_BIN="$HOOK_STUB_ROOT/bin"
export HOOK_STUB_LOG="$HOOK_STUB_ROOT/invocations"
: > "$HOOK_STUB_LOG"

# shellcheck disable=SC2016  # single quotes defer expansion into the check subshell
check "claude-event-hook logs a normal tool but excludes mcp__odoo-sdk__* tools" bash -c '
  emit() {
    printf "{\"session_id\":\"s1\",\"tool_name\":\"%s\",\"hook_event_name\":\"PreToolUse\",\"cwd\":\"/tmp\"}" "$1" \
      | PATH="$HOOK_STUB_BIN:$PATH" /usr/local/bin/claude-event-hook PreToolUse
  }
  # An EXCLUDED tool exits before the shim forks anything, so the log is settled
  # the moment emit returns. A LOGGED tool forks a detached job, so poll for it.
  emit mcp__odoo-sdk__get_tasks
  emit Bash
  for _ in $(seq 1 50); do
    grep -q -- "--subject Bash" "$HOOK_STUB_LOG" && break
    sleep 0.2
  done
  # Bash was emitted AFTER the odoo tool, so if a regression made the shim fork
  # an odoo write too, that write was queued first - but it is detached, so give
  # it a grace period to land rather than racing the negative assertion below.
  sleep 1

  grep -q -- "--source claude:PreToolUse" "$HOOK_STUB_LOG" \
    || { echo "shim never invoked odoo-sdk for a non-odoo PreToolUse tool" >&2; exit 1; }
  grep -q -- "--subject Bash" "$HOOK_STUB_LOG" \
    || { echo "shim did not forward --subject Bash" >&2; exit 1; }
  if grep -q -- "mcp__odoo-sdk__" "$HOOK_STUB_LOG"; then
    echo "shim logged an mcp__odoo-sdk__* tool the MCP server already logs server-side" >&2
    exit 1
  fi
  # Exactly one row: proves the exclusion dropped the odoo call rather than the
  # assertions above merely failing to notice a second, differently-shaped one.
  [ "$(wc -l < "$HOOK_STUB_LOG")" -eq 1 ] \
    || { echo "expected exactly 1 odoo-sdk invocation, got $(wc -l < "$HOOK_STUB_LOG")" >&2; exit 1; }
'
rm -rf "$HOOK_STUB_ROOT"
unset HOOK_STUB_BIN HOOK_STUB_LOG

# The shim must always exit 0 and pass --attach-active-run to odoo-sdk.
check "claude-event-hook attaches the active run" bash -c \
  "grep -q -- '--attach-active-run' /usr/local/bin/claude-event-hook"

# The shim must no-op (exit 0) when odoo-sdk is absent from PATH. Run it with a
# stripped PATH (coreutils only) so `odoo-sdk` cannot be found and pipe it an
# empty payload; a nonzero exit here would block a real Claude session.
check "claude-event-hook no-ops with exit 0 when odoo-sdk is absent" bash -c \
  "printf '{}' | PATH=/usr/bin:/bin /usr/local/bin/claude-event-hook PreToolUse; test \$? -eq 0"

# #411: hook<->CLI CONTRACT, exercised end to end. The grep guards above only
# prove the flag STRINGS survive in the shim text; they cannot catch a rename on
# the SDK side. Because the shim swallows every failure (always exit 0) and forks
# the SDK call into a DETACHED background job, a rename of --attach-active-run /
# --payload or of the `claude:` source prefix would drop every event in
# production while passing all of the above. So drive the REAL claude-event-hook
# with a representative PreToolUse payload and assert a row actually LANDED,
# carrying the trimmed --payload and (proof of the whole vector) still MATCHING
# the billing predicate that keys on the `claude:` prefix. A flag/prefix drift
# fails this loudly.
#
# Self-contained by design: it provisions its OWN throwaway tracker DB with the
# SDK schema and points the shim at it via ODOO_TASK_TRACKER_DIR, so it runs
# deterministically whether or not a host-provisioned central DB is mounted (it
# is under CI's setup.sh, but NOT under a plain `devcontainer features test`) and
# never touches the real DB. Gated on the SDK being installed (absent on <3.10
# images); the SDK bin dir is put on PATH so the shim's bare `odoo-sdk` resolves
# to the real installed CLI. `odoo-sdk` is deliberately NOT on the default PATH
# (only odoo-mcp/odoo-tui are symlinked), so this uses the venv bin explicitly.
# shellcheck disable=SC2016  # single quotes defer expansion into the check subshell
check "claude-event-hook drives a real PreToolUse event through --attach-active-run/--payload into a provisioned DB" bash -c '
  SDK_BIN=/usr/local/share/uv/tools/odoo-sdk/bin
  test -x "$SDK_BIN/odoo-sdk" || exit 0
  STATE="$(mktemp -d)"
  DB="$STATE/tracker.db"
  # Provision a throwaway central DB with the SDK schema (never the real one).
  "$SDK_BIN/python" -c "import sqlite3, sys; from odoo_sdk.state.db import create_schema; c = sqlite3.connect(sys.argv[1]); create_schema(c); c.commit(); c.close()" "$DB" \
    || { echo "failed to provision temp tracker DB at $DB" >&2; rm -rf "$STATE"; exit 1; }
  subj="ci-hook-e2e-$$"
  printf "{\"session_id\":\"s-%s\",\"tool_name\":\"%s\",\"hook_event_name\":\"PreToolUse\",\"cwd\":\"/tmp\"}" "$$" "$subj" \
    | ODOO_TASK_TRACKER_DIR="$STATE" PATH="$SDK_BIN:$PATH" /usr/local/bin/claude-event-hook PreToolUse
  # The shim fires the SDK write in a DETACHED background job, so poll the DB.
  for _ in $(seq 1 50); do
    "$SDK_BIN/python" - "$DB" "$subj" <<PY && { rm -rf "$STATE"; exit 0; }
import json, sqlite3, sys
from odoo_sdk.state.db import _DEVELOPMENT_SOURCE_PREDICATE
db, subj = sys.argv[1], sys.argv[2]
conn = sqlite3.connect(db)
row = conn.execute(
    f"SELECT source, payload FROM events WHERE subject = ? AND {_DEVELOPMENT_SOURCE_PREDICATE}",
    (subj,),
).fetchone()
if row is None:
    sys.exit(1)
source, payload = row
assert source == "claude:PreToolUse", source
assert json.loads(payload)["tool_name"] == subj, payload
sys.exit(0)
PY
    sleep 0.2
  done
  echo "no billing-eligible claude:PreToolUse row for subject $subj ever landed" >&2
  rm -rf "$STATE"
  exit 1
'

# Behavioural checks for sync-claude-hooks against a throwaway CLAUDE_CONFIG_DIR.
HOOKS_TEST_ROOT="$(mktemp -d)"

# (a) No settings.json → created, valid JSON, contains all feature hook entries.
HK_A="$HOOKS_TEST_ROOT/a"
mkdir -p "$HK_A"
check "sync-claude-hooks creates settings.json when absent" bash -c \
  "CLAUDE_CONFIG_DIR=\"$HK_A\" /usr/local/bin/sync-claude-hooks && test -f \"$HK_A/settings.json\""
check "created settings.json is valid JSON" bash -c "jq . \"$HK_A/settings.json\" >/dev/null"
check "settings.json contains the feature PreToolUse hook (match-all matcher)" bash -c \
  "[ \"\$(jq -r '.hooks.PreToolUse[0].matcher' \"$HK_A/settings.json\")\" = '*' ] && jq -e '.hooks.PreToolUse[] | select(.hooks[].command | contains(\"claude-event-hook PreToolUse\"))' \"$HK_A/settings.json\" >/dev/null"
check "settings.json contains all seven feature hook events" bash -c \
  "for ev in SessionStart UserPromptSubmit PreToolUse SubagentStart SubagentStop Stop SessionEnd; do jq -e --arg e \"\$ev\" '.hooks[\$e][] | select(.hooks[].command | contains(\"claude-event-hook\"))' \"$HK_A/settings.json\" >/dev/null || exit 1; done"

# (b) Running the sync TWICE yields no duplicate feature entries.
check "sync-claude-hooks is idempotent (no duplicate PreToolUse groups on re-run)" bash -c \
  "CLAUDE_CONFIG_DIR=\"$HK_A\" /usr/local/bin/sync-claude-hooks && [ \"\$(jq '[.hooks.PreToolUse[] | select(.hooks[].command | contains(\"claude-event-hook\"))] | length' \"$HK_A/settings.json\")\" = '1' ]"

# (c) A pre-seeded user setting AND a user-authored hook survive the merge.
HK_B="$HOOKS_TEST_ROOT/b"
mkdir -p "$HK_B"
cat > "$HK_B/settings.json" <<'JSON'
{ "model": "opus", "env": {"FOO": "bar"},
  "hooks": {
    "PreToolUse": [ {"matcher": "Bash", "hooks": [{"type":"command","command":"/home/me/my-own-hook.sh"}]} ]
  } }
JSON
check "sync-claude-hooks merges into a user-populated settings.json" bash -c \
  "CLAUDE_CONFIG_DIR=\"$HK_B\" /usr/local/bin/sync-claude-hooks"
check "a pre-seeded user setting survives the merge" bash -c \
  "[ \"\$(jq -r '.model' \"$HK_B/settings.json\")\" = 'opus' ] && [ \"\$(jq -r '.env.FOO' \"$HK_B/settings.json\")\" = 'bar' ]"
check "a user-authored hook survives the merge" bash -c \
  "jq -e '.hooks.PreToolUse[] | select(.hooks[].command == \"/home/me/my-own-hook.sh\")' \"$HK_B/settings.json\" >/dev/null"
check "the feature hook is added alongside the user's (two PreToolUse groups)" bash -c \
  "[ \"\$(jq '.hooks.PreToolUse | length' \"$HK_B/settings.json\")\" = '2' ]"

# (d) A corrupt/unparseable settings.json is left strictly alone (never destroy
# the user's real config).
HK_C="$HOOKS_TEST_ROOT/c"
mkdir -p "$HK_C"
printf '{ this is : not json ' > "$HK_C/settings.json"
check "sync-claude-hooks leaves a corrupt settings.json untouched and exits 0" bash -c \
  "before=\$(cat \"$HK_C/settings.json\"); CLAUDE_CONFIG_DIR=\"$HK_C\" /usr/local/bin/sync-claude-hooks; rc=\$?; [ \$rc -eq 0 ] && [ \"\$before\" = \"\$(cat \"$HK_C/settings.json\")\" ]"

rm -rf "$HOOKS_TEST_ROOT"

# Regression guard for #233: the credential-holding config dirs must be 0700,
# not the umask default 0755, or real secrets (e.g. ~/.claude/.credentials.json,
# gh's hosts.yml) live in a world-readable dir. The mode comes from
# persisted-paths.tsv's `mode` column and is enforced by BOTH consumers that
# create these dirs: install.sh chmods the container-side targets, and setup.sh
# chmods the host-side sources. Both matter, and these assertions cover
# whichever is visible: CI runs `sh ./setup.sh` before this test, so the
# feature's bind mounts ARE active here and stat sees the HOST dirs' modes
# through the mount; in a mountless run (e.g. `devcontainer features test`
# without the host dirs) stat sees install.sh's chmod instead. Same manifest
# column either way, so the expected values are identical.
# pr-automation holds no credentials and deliberately stays 0755. shell-history
# is 0777 (world-writable): its host dir is bind-mounted over the container dir,
# so a container user whose uid differs from the host owner could not otherwise
# create/append bash_history and every command printed a "cannot create:
# Permission denied" error (#323); world-writable lets any uid write it.
# NOTE: stat -c '%a' prints octal WITHOUT a leading zero (700 / 755 / 777).
check "claude-home is chmod 0700 (credentials not world-readable)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/claude-home)\" = '700' ]"
check "gh-cli-config is chmod 0700 (credentials not world-readable)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/gh-cli-config)\" = '700' ]"
check "odoo-sdk-config is chmod 0700 (credentials not world-readable)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/odoo-sdk-config)\" = '700' ]"
check "coderabbit-config is chmod 0700 (credentials not world-readable)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/coderabbit-config)\" = '700' ]"
check "pr-automation dir stays 0755 (holds no credentials)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/pr-automation)\" = '755' ]"
check "shell-history dir is 0777 (any uid can create/append bash_history, #323)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/shell-history)\" = '777' ]"

reportResults
