#!/bin/bash

# This test file is executed against an auto-generated devcontainer.json that
# includes the 'personal-features' Feature alone (it has no options - this
# Feature is the owner's personal, opinionated setup, so everything below is
# always installed).
#
# Installing Claude Code requires npm, so the autogenerated job in
# .github/workflows/test.yaml runs this against Node-enabled base images
# rather than bare debian/ubuntu - see src/personal-features/NOTES.md for why
# Node isn't bundled into this Feature itself.
#
# This test can be run with the following command:
#
#    devcontainer features test \
#               --features personal-features \
#               --remote-user root \
#               --skip-scenarios \
#               --base-image mcr.microsoft.com/devcontainers/javascript-node:latest \
#               /path/to/this/repo

set -e

source dev-container-features-test-lib

check "claude wrapper is on PATH and executable" bash -c "test -x \"\$(command -v claude)\""
check "claude reports a version" claude --version

check "wrapper injects --ide for default sessions" bash -c "grep -q -- '--ide' \"\$(command -v claude)\""
check "wrapper passes known subcommands through untouched" bash -c "grep -q 'mcp' \"\$(command -v claude)\""

check "claude config dir exists" bash -c "test -d /usr/local/share/claude-home"
check "gh config dir exists" bash -c "test -d /usr/local/share/gh-cli-config"
check "CLAUDE_CONFIG_DIR points at the bind mount" bash -c "[ \"\$CLAUDE_CONFIG_DIR\" = '/usr/local/share/claude-home' ]"
check "GH_CONFIG_DIR points at the bind mount" bash -c "[ \"\$GH_CONFIG_DIR\" = '/usr/local/share/gh-cli-config' ]"

# odoo-sdk MCP server is registered at user scope when the odoo-mcp binary was
# installed (skipped on <3.10 base images where the SDK wheel isn't installed).
check "odoo-sdk MCP server is registered when odoo-mcp is present" bash -c \
  "! test -x /usr/local/bin/odoo-mcp || claude mcp get odoo-sdk"

# Regression guard for #120: the odoo-tui curses TUI console script is symlinked
# onto PATH whenever the SDK is installed (i.e. whenever odoo-mcp is present).
# Scoped the same way as the MCP check so it no-ops on <3.10 base images where
# the SDK wheel isn't installed.
check "odoo-tui console script is on PATH when the SDK is installed" bash -c \
  "! test -x /usr/local/bin/odoo-mcp || test -x \"\$(command -v odoo-tui)\""

# Regression guard for #115: the feature must NOT force the task-tracker state
# onto the root-provisioned /usr/local/share path via ODOO_TASK_TRACKER_DIR.
# That path is chown'd to the build-time user (uid mismatch with the runtime
# odoo user), so it lands unwritable and every FSM tool that writes a session
# file fails with EACCES. With the override gone, the SDK falls back to the
# runtime user's own $XDG_STATE_HOME/~/.local/state, which it owns and can
# write. Assert the override isn't reintroduced pointing back at that path, and
# that the feature no longer provisions the unwritable dir.
check "ODOO_TASK_TRACKER_DIR does not force the unwritable root state path" bash -c \
  "[ \"\$ODOO_TASK_TRACKER_DIR\" != '/usr/local/share/odoo-task-tracker' ]"
check "task-tracker state dir is not root-provisioned in /usr/local/share" bash -c \
  "! test -d /usr/local/share/odoo-task-tracker"

# productivity/navigation CLIs
check "ripgrep is installed" rg --version
check "fd is installed" fd --version
check "fzf is installed" fzf --version
check "bat is installed" bat --version
check "jq is installed" jq --version
check "yq is installed" yq --version
check "eza is installed" eza --version
check "zoxide is installed" zoxide --version
check "tldr is installed" tldr --version

# secret scanning
check "gitleaks is installed" gitleaks version

# create-pr (config-driven gh pr create wrapper)
check "create-pr is installed and executable" bash -c "test -x /usr/local/bin/create-pr"
check "create-pr passes shell syntax check" bash -c "sh -n /usr/local/bin/create-pr"
check "PR_AUTOMATION_CONFIG_DIR points at the bind mount" bash -c \
  "[ \"\$PR_AUTOMATION_CONFIG_DIR\" = '/usr/local/share/pr-automation' ]"
check "pr-automation config dir exists" bash -c "test -d /usr/local/share/pr-automation"

# CodeRabbit CLI (best-effort install; check the binary is present + on PATH)
check "coderabbit is installed" bash -c "test -x \"\$(command -v coderabbit)\""
check "coderabbit config dir exists" bash -c "test -d /usr/local/share/coderabbit-config"
check "CODERABBIT_CONFIG_DIR points at the bind mount" bash -c "[ \"\$CODERABBIT_CONFIG_DIR\" = '/usr/local/share/coderabbit-config' ]"

# global git hooks
check "global core.hooksPath is configured" bash -c "[ \"\$(git config --system --get core.hooksPath)\" = '/usr/local/share/git-hooks' ]"
check "global commit-msg hook is executable" bash -c "test -x /usr/local/share/git-hooks/commit-msg"
check "global pre-commit hook is executable" bash -c "test -x /usr/local/share/git-hooks/pre-commit"

# shell enhancements
check "starship is installed" starship --version
check "shell history dir exists" bash -c "test -d /usr/local/share/shell-history"
check "~/.bash_history is linked to the bind-mounted history file" bash -c \
  "[ \"\$(readlink -f \"\$HOME/.bash_history\")\" = '/usr/local/share/shell-history/bash_history' ]"
check "starship.toml was placed in global share" bash -c "test -f /usr/local/share/starship.toml"
check "shell snippet was appended to global bashrc" bash -c "grep -q 'personal-features' /etc/bash.bashrc"

reportResults
