#!/bin/bash

# This test file is executed against an auto-generated devcontainer.json that
# includes the 'personal-features' Feature alone (it has no options - this
# Feature is the owner's personal, opinionated setup, so everything below is
# always installed).
#
# Installing Claude Code requires npm, so the autogenerated job in
# .github/workflows/test.yaml runs this against Node-enabled base images
# rather than bare debian/ubuntu - see src/personal-features/NOTES.md for why
# Node isn't bundled into this Feature itself.
#
# This test can be run with the following command:
#
#    devcontainer features test \
#               --features personal-features \
#               --remote-user root \
#               --skip-scenarios \
#               --base-image mcr.microsoft.com/devcontainers/javascript-node:latest \
#               /path/to/this/repo

set -e

source dev-container-features-test-lib

check "claude wrapper is on PATH and executable" bash -c "test -x \"\$(command -v claude)\""
check "claude reports a version" claude --version

# The wrapper injects --ide ONLY for a bare interactive session (no args + TTY)
# and passes everything else straight through, so a new Claude Code subcommand
# can never be mangled into `claude --ide <subcommand>` (see NOTES.md). Assert
# the guard (`$# -eq 0` + `[ -t 0 ]`) and the verbatim passthrough exec are
# present, and that no stale subcommand allowlist (`case "$1" in`) survives.
check "wrapper injects --ide only for a bare interactive session" bash -c \
  "grep -qF -- '\$# -eq 0' \"\$(command -v claude)\" && grep -qF -- '[ -t 0 ]' \"\$(command -v claude)\" && grep -qF -- 'exec \"\$REAL\" --ide' \"\$(command -v claude)\""
check "wrapper passes everything else (subcommands, flags, prompts) through untouched" bash -c \
  "grep -qF -- 'exec \"\$REAL\" \"\$@\"' \"\$(command -v claude)\""
check "wrapper has no hardcoded subcommand allowlist" bash -c \
  "! grep -qF 'case \"\$1\" in' \"\$(command -v claude)\""

check "claude config dir exists" bash -c "test -d /usr/local/share/claude-home"
check "gh config dir exists" bash -c "test -d /usr/local/share/gh-cli-config"
check "odoo-sdk config dir exists" bash -c "test -d /usr/local/share/odoo-sdk-config"
check "CLAUDE_CONFIG_DIR points at the bind mount" bash -c "[ \"\$CLAUDE_CONFIG_DIR\" = '/usr/local/share/claude-home' ]"
check "GH_CONFIG_DIR points at the bind mount" bash -c "[ \"\$GH_CONFIG_DIR\" = '/usr/local/share/gh-cli-config' ]"

# NOTE: no check here that the odoo-sdk MCP server is registered. install.sh
# registers it at BUILD time into CLAUDE_CONFIG_DIR=/usr/local/share/claude-home,
# but at RUNTIME that directory is shadowed by the feature's bind mount of the
# host's ~/.claude (empty on CI runners and fresh hosts), so `claude mcp get
# odoo-sdk` reports the server as missing whenever the mount is active - i.e.
# always in real use. Asserting it here would test something the feature cannot
# deliver; a runtime-registration mechanism (e.g. a feature-contributed
# postCreateCommand) is a separate product decision.

# Regression guard for #120: the odoo-tui curses TUI console script is symlinked
# onto PATH whenever the SDK is installed (i.e. whenever odoo-mcp is present).
# Gated on the odoo-mcp binary so it no-ops on <3.10 base images where the SDK
# wheel isn't installed. PATH checks are unaffected by the bind mounts above.
check "odoo-tui console script is on PATH when the SDK is installed" bash -c \
  "! test -x /usr/local/bin/odoo-mcp || test -x \"\$(command -v odoo-tui)\""

# Regression guard for #115: the feature must NOT force the task-tracker state
# onto the root-provisioned /usr/local/share path via ODOO_TASK_TRACKER_DIR.
# That path is chown'd to the build-time user (uid mismatch with the runtime
# odoo user), so it lands unwritable and every FSM tool that writes a session
# file fails with EACCES. With the override gone, the SDK falls back to the
# runtime user's own $XDG_STATE_HOME/~/.local/state, which it owns and can
# write. Assert the override isn't reintroduced pointing back at that path, and
# that the feature no longer provisions the unwritable dir.
check "ODOO_TASK_TRACKER_DIR does not force the unwritable root state path" bash -c \
  "[ \"\$ODOO_TASK_TRACKER_DIR\" != '/usr/local/share/odoo-task-tracker' ]"
check "task-tracker state dir is not root-provisioned in /usr/local/share" bash -c \
  "! test -d /usr/local/share/odoo-task-tracker"

# productivity/navigation CLIs
check "ripgrep is installed" rg --version
check "fd is installed" fd --version
check "fzf is installed" fzf --version
check "bat is installed" bat --version
check "jq is installed" jq --version
check "yq is installed" yq --version
check "eza is installed" eza --version
check "zoxide is installed" zoxide --version
check "tldr is installed" tldr --version

# secret scanning
check "gitleaks is installed" gitleaks version

# create-pr (config-driven gh pr create wrapper)
check "create-pr is installed and executable" bash -c "test -x /usr/local/bin/create-pr"
check "create-pr passes shell syntax check" bash -c "sh -n /usr/local/bin/create-pr"
check "PR_AUTOMATION_CONFIG_DIR points at the bind mount" bash -c \
  "[ \"\$PR_AUTOMATION_CONFIG_DIR\" = '/usr/local/share/pr-automation' ]"
check "pr-automation config dir exists" bash -c "test -d /usr/local/share/pr-automation"

# CodeRabbit CLI (best-effort install; check the binary is present + on PATH)
check "coderabbit is installed" bash -c "test -x \"\$(command -v coderabbit)\""
check "coderabbit config dir exists" bash -c "test -d /usr/local/share/coderabbit-config"
check "CODERABBIT_CONFIG_DIR points at the bind mount" bash -c "[ \"\$CODERABBIT_CONFIG_DIR\" = '/usr/local/share/coderabbit-config' ]"

# global git hooks
check "global core.hooksPath is configured" bash -c "[ \"\$(git config --system --get core.hooksPath)\" = '/usr/local/share/git-hooks' ]"
check "global commit-msg hook is executable" bash -c "test -x /usr/local/share/git-hooks/commit-msg"
check "global pre-commit hook is executable" bash -c "test -x /usr/local/share/git-hooks/pre-commit"

# shell enhancements
check "starship is installed" starship --version
check "shell history dir exists" bash -c "test -d /usr/local/share/shell-history"
check "~/.bash_history is linked to the bind-mounted history file" bash -c \
  "[ \"\$(readlink -f \"\$HOME/.bash_history\")\" = '/usr/local/share/shell-history/bash_history' ]"

# Regression guard for #198: shell history is bind-mounted as a *directory*, not
# as a single file. Docker Desktop materialises a missing single-file mount
# source as a directory on the host, which then fails the mount - so the mount
# target must be the directory, with the history file living inside it.
check "shell history mount target is a directory, not a file" bash -c \
  "test -d /usr/local/share/shell-history && ! test -L /usr/local/share/shell-history"

# Regression guard for #198: on a first run against an empty host directory the
# history file doesn't exist yet, so the ~/.bash_history symlink is dangling.
# That has to self-heal - bash opens HISTFILE with O_CREAT, which follows the
# symlink and creates the target. Simulate it by removing the file first.
check "a dangling history symlink self-heals on first write" bash -c \
  "rm -f /usr/local/share/shell-history/bash_history \
   && printf 'echo 198\n' >> \"\$HOME/.bash_history\" \
   && test -f /usr/local/share/shell-history/bash_history"

# Regression guard for #198: HISTFILE is set system-wide (so history persists
# for every user, not just the one whose home was symlinked), and histappend is
# a correctness fix - without it bash truncates HISTFILE on exit and rewrites it
# from memory, so one shell exiting would wipe a concurrent container's history.
check "HISTFILE points at the bind-mounted history file" bash -c \
  "grep -q '^export HISTFILE=/usr/local/share/shell-history/bash_history$' /etc/bash.bashrc"
check "histappend is enabled so concurrent shells don't truncate history" bash -c \
  "grep -q '^shopt -s histappend$' /etc/bash.bashrc"

# Regression guard for #198: assert the *runtime* value, not just the file. Both
# `starship init` and `zoxide init` overwrite PROMPT_COMMAND, so if the flush is
# set before them in the snippet it is silently dropped and history is only
# written on a clean exit (losing it whenever the container is killed).
# /etc/bash.bashrc is guarded by `[ -z "$PS1" ] && return`, so this has to run an
# interactive shell to see the assembled value at all.
check "history -a survives starship/zoxide clobbering PROMPT_COMMAND" bash -ic \
  "[[ \$PROMPT_COMMAND == *'history -a'* ]]"

check "starship.toml was placed in global share" bash -c "test -f /usr/local/share/starship.toml"
check "shell snippet was appended to global bashrc" bash -c "grep -q 'personal-features' /etc/bash.bashrc"

# Regression guard for #233: the credential-holding config dirs must be 0700,
# not the umask default 0755, or real secrets (e.g. ~/.claude/.credentials.json,
# gh's hosts.yml) live in a world-readable dir. The mode comes from
# persisted-paths.tsv's `mode` column and is enforced by BOTH consumers that
# create these dirs: install.sh chmods the container-side targets, and setup.sh
# chmods the host-side sources. Both matter, and these assertions cover
# whichever is visible: CI runs `sh ./setup.sh` before this test, so the
# feature's bind mounts ARE active here and stat sees the HOST dirs' modes
# through the mount; in a mountless run (e.g. `devcontainer features test`
# without the host dirs) stat sees install.sh's chmod instead. Same manifest
# column either way, so the expected values are identical.
# The non-credential dirs (pr-automation, shell-history) deliberately stay 0755.
# NOTE: stat -c '%a' prints octal WITHOUT a leading zero (700 / 755).
check "claude-home is chmod 0700 (credentials not world-readable)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/claude-home)\" = '700' ]"
check "gh-cli-config is chmod 0700 (credentials not world-readable)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/gh-cli-config)\" = '700' ]"
check "odoo-sdk-config is chmod 0700 (credentials not world-readable)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/odoo-sdk-config)\" = '700' ]"
check "coderabbit-config is chmod 0700 (credentials not world-readable)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/coderabbit-config)\" = '700' ]"
check "pr-automation dir stays 0755 (holds no credentials)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/pr-automation)\" = '755' ]"
check "shell-history dir stays 0755 (holds no credentials)" bash -c \
  "[ \"\$(stat -c '%a' /usr/local/share/shell-history)\" = '755' ]"

reportResults
