#!/bin/bash

# This test file is executed against an auto-generated devcontainer.json that
# includes the 'claude' Feature alone with default options (it has none).
#
# Installing Claude Code requires npm, so the autogenerated job in
# .github/workflows/test.yaml runs this against Node-enabled base images
# rather than bare debian/ubuntu - see src/claude/NOTES.md for why Node
# isn't bundled into this Feature itself.
#
# This test can be run with the following command:
#
#    devcontainer features test \
#               --features claude \
#               --remote-user root \
#               --skip-scenarios \
#               --base-image mcr.microsoft.com/devcontainers/javascript-node:latest \
#               /path/to/this/repo

set -e

source dev-container-features-test-lib

check "claude wrapper is on PATH and executable" bash -c "test -x \"\$(command -v claude)\""
check "claude reports a version" claude --version

check "wrapper injects --ide for default sessions" bash -c "grep -q -- '--ide' \"\$(command -v claude)\""
check "wrapper passes known subcommands through untouched" bash -c "grep -q 'mcp' \"\$(command -v claude)\""

check "claude config volume is mounted" bash -c "test -d /usr/local/share/claude-code-home"
check "gh config volume is mounted" bash -c "test -d /usr/local/share/gh-cli-config"
check "~/.claude is symlinked into the persisted volume" bash -c "test -L \"\$HOME/.claude\""
check "~/.claude.json is symlinked into the persisted volume" bash -c "test -L \"\$HOME/.claude.json\""
check "GH_CONFIG_DIR points at the persisted volume" bash -c "[ \"\$GH_CONFIG_DIR\" = '/usr/local/share/gh-cli-config' ]"

reportResults
