#!/bin/bash

# Scenario 'with_kb_mounted' (see scenarios.json): the 'second-brain' Feature
# on the plain ubuntu base image with a non-root remoteUser (vscode), proving
# the mount is visible and usable without root.
#
# PREREQUISITES (the dedicated job in .github/workflows/test.yaml provides
# both; replicate them for a local run):
#
#    export SECOND_BRAIN_DIR="$(mktemp -d)"
#    chmod 0777 "$SECOND_BRAIN_DIR"                # vscode (uid 1000) != runner uid
#    echo 'host knowledge survives' > "$SECOND_BRAIN_DIR/host-sentinel.md"
#    devcontainer features test -p ./devcontainer-features \
#               -f second-brain --skip-autogenerated --skip-duplicated \
#               --filter with_kb_mounted .

set -e

# shellcheck source=/dev/null  # dev-container-features-test-lib is injected by the test harness at runtime; not resolvable statically. check()/reportResults() come from it.
source dev-container-features-test-lib

check "running as the non-root remoteUser" bash -c "[ \"\$(id -un)\" = 'vscode' ]"

check "knowledge base target is a real mountpoint" bash -c \
  "awk -v t=/mnt/second-brain '\$5 == t { found = 1 } END { exit !found }' /proc/self/mountinfo"
check "second-brain-verify passes against the live mount" second-brain-verify

# The sentinel is written on the HOST by the CI job before the container is
# created - seeing its content in-container proves the target really is the
# host knowledge base, not a fresh directory materialised by the runtime.
check "host-seeded content is visible in the container" bash -c \
  "grep -q 'host knowledge survives' /mnt/second-brain/host-sentinel.md"

# Read-write for the non-root user (the CI job chmods the host dir 0777: bind
# mounts preserve host ownership, and the runner's uid differs from vscode's).
check "non-root user can write to the knowledge base" bash -c \
  "marker=/mnt/second-brain/.scenario-write-\$\$; echo second-brain-rw > \"\$marker\" && grep -q second-brain-rw \"\$marker\" && rm \"\$marker\""

check "SECOND_BRAIN_DIR (containerEnv) points at the mount target" bash -c \
  "[ \"\$SECOND_BRAIN_DIR\" = '/mnt/second-brain' ]"

# Report result
reportResults
