#!/bin/bash

# This test file is executed against an auto-generated devcontainer.json that
# includes the 'personal-features' Feature alone with default options (it has none).
#
# Installing Claude Code requires npm, so the autogenerated job in
# .github/workflows/test.yaml runs this against Node-enabled base images
# rather than bare debian/ubuntu - see src/personal-features/NOTES.md for why
# Node isn't bundled into this Feature itself.
#
# This test can be run with the following command:
#
#    devcontainer features test \
#               --features personal-features \
#               --remote-user root \
#               --skip-scenarios \
#               --base-image mcr.microsoft.com/devcontainers/javascript-node:latest \
#               /path/to/this/repo

set -e

source dev-container-features-test-lib

check "claude wrapper is on PATH and executable" bash -c "test -x \"\$(command -v claude)\""
check "claude reports a version" claude --version

check "wrapper injects --ide for default sessions" bash -c "grep -q -- '--ide' \"\$(command -v claude)\""
check "wrapper passes known subcommands through untouched" bash -c "grep -q 'mcp' \"\$(command -v claude)\""

check "claude config volume is mounted" bash -c "test -d /usr/local/share/claude-code-home"
check "gh config volume is mounted" bash -c "test -d /usr/local/share/gh-cli-config"
check "~/.claude is symlinked into the persisted volume" bash -c "test -L \"\$HOME/.claude\""
check "~/.claude.json is symlinked into the persisted volume" bash -c "test -L \"\$HOME/.claude.json\""
check "GH_CONFIG_DIR points at the persisted volume" bash -c "[ \"\$GH_CONFIG_DIR\" = '/usr/local/share/gh-cli-config' ]"

# cliTools (default true)
check "ripgrep is installed" rg --version
check "fd is installed" fd --version
check "fzf is installed" fzf --version
check "bat is installed" bat --version
check "jq is installed" jq --version
check "yq is installed" yq --version
check "eza is installed" eza --version
check "zoxide is installed" zoxide --version
check "tldr is installed" tldr --version

# secretsScanning (default true)
check "gitleaks is installed" gitleaks version

# gitHooks (default true)
check "global core.hooksPath is configured" bash -c "[ \"\$(git config --system --get core.hooksPath)\" = '/usr/local/share/git-hooks' ]"
check "global commit-msg hook is executable" bash -c "test -x /usr/local/share/git-hooks/commit-msg"
check "global pre-commit hook is executable" bash -c "test -x /usr/local/share/git-hooks/pre-commit"

# shellEnhancements (default false)
check "shell history volume is mounted" bash -c "test -d /usr/local/share/shell-history"

reportResults
