#!/bin/bash

# Executed against the 'with_shell_enhancements' scenario in scenarios.json,
# which opts into the shellEnhancements option (default false) to cover the
# Starship prompt / alias snippet / persisted shell history path that the
# autogenerated test (default options) doesn't exercise.

set -e

source dev-container-features-test-lib

check "starship is installed" starship --version
check "shell history volume is mounted" bash -c "test -d /usr/local/share/shell-history"
check "~/.bash_history is symlinked into the persisted volume" bash -c "test -L \"\$HOME/.bash_history\""
check "~/.zsh_history is symlinked into the persisted volume" bash -c "test -L \"\$HOME/.zsh_history\""
check "shell snippet was appended to .bashrc" bash -c "grep -q 'personal-features' \"\$HOME/.bashrc\""

reportResults
